# Generated by Django 3.1 on 2020-08-21 18:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('midle_name', models.CharField(max_length=64, verbose_name='Отчетство')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('delo_id', models.IntegerField(verbose_name='Дело ID пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('delo_id', models.IntegerField(verbose_name='Дело ID темы')),
            ],
        ),
    ]
