# Generated by Django 3.1 on 2020-08-21 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200821_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Тема обращения')),
                ('destination', models.CharField(max_length=64, verbose_name='Адресат обращения')),
                ('status', models.IntegerField(choices=[(0, 'Новое'), (1, 'В работе'), (2, 'Перенаправлено'), (3, 'Требуется ответ гражданина'), (10, 'Завершено')], default=0)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 8, 21, 23, 23, 46, 85163))),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterField(
            model_name='subject',
            name='first_name',
            field=models.CharField(default='Не задано', max_length=64, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apeals',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', related_query_name='subject', to='dashboard.subject'),
        ),
    ]
