# Generated by Django 3.1 on 2020-08-21 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200821_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeals',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', related_query_name='form', to='dashboard.externalform'),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 23, 42, 39, 176583)),
        ),
    ]
