# Generated by Django 3.1 on 2020-08-21 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200821_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='IYNXWzfFGZw8claLyi8YFImywtgjBWrR', max_length=32),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 0, 0, 25, 229244)),
        ),
    ]
