# Generated by Django 3.1 on 2020-08-21 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('dashboard', '0006_auto_20200822_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 0, 9, 16, 717791)),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', related_query_name='form', to='api.externalform'),
        ),
        migrations.DeleteModel(
            name='ExternalForm',
        ),
    ]
