# Generated by Django 3.1 on 2020-08-21 23:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200822_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 2, 29, 18, 61150)),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', related_query_name='subject', to='dashboard.subject'),
        ),
    ]
