# Generated by Django 3.1 on 2020-08-22 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200822_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apeals',
            name='title',
        ),
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 3, 45, 51, 799180)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='delo_id',
            field=models.IntegerField(default=0, verbose_name='Дело ID пользователя'),
        ),
    ]
