# Generated by Django 3.1 on 2020-08-22 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200822_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 4, 41, 27, 493369)),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='destination',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Адресат обращения'),
        ),
    ]
