# Generated by Django 3.1 on 2020-08-22 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200822_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeals',
            name='format',
            field=models.IntegerField(choices=[(0, 'email'), (1, 'forms')], default=0),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 15, 10, 18, 59611)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя'),
        ),
    ]
