# Generated by Django 3.1 on 2020-08-22 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200822_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 15, 11, 56, 303265)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='addres_arr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
