# Generated by Django 3.1 on 2020-08-22 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200822_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeals',
            name='delo_id',
            field=models.IntegerField(default=0, verbose_name='Дело ID обращения'),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 15, 12, 43, 195117)),
        ),
    ]
