# Generated by Django 3.1 on 2020-08-22 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200822_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 15, 22, 1, 449659)),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='format',
            field=models.IntegerField(choices=[(0, 'froms'), (1, 'email')], default=0),
        ),
    ]
