# Generated by Django 3.1 on 2020-08-22 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200822_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 17, 3, 53, 503100)),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='destination',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адресат обращения'),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='topic',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тема обращения'),
        ),
    ]
