# Generated by Django 3.1 on 2020-08-22 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200822_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 17, 39, 24, 604375)),
        ),
        migrations.CreateModel(
            name='ApealsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 8, 22, 17, 39, 24, 604956))),
                ('apeals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apeal', related_query_name='apeal', to='dashboard.apeals')),
            ],
        ),
    ]
