# Generated by Django 3.1 on 2020-08-22 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20200822_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 22, 56, 1, 23575)),
        ),
        migrations.AlterField(
            model_name='apealscomments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 22, 56, 1, 24293)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='addres_arr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
