# Generated by Django 3.1 on 2020-08-22 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200822_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 23, 5, 50, 157824)),
        ),
        migrations.AlterField(
            model_name='apealscomments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 23, 5, 50, 158568)),
        ),
    ]
