# Generated by Django 3.1 on 2020-08-22 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20200822_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeals',
            name='uid',
            field=models.CharField(default='EoH0V3Cu', max_length=16),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 1, 37, 24, 109276)),
        ),
        migrations.AlterField(
            model_name='apeals',
            name='format',
            field=models.IntegerField(choices=[(0, 'Обращения с формы'), (1, 'Email обращения'), (2, 'Входящий звонок')], default=0),
        ),
        migrations.AlterField(
            model_name='apealscomments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 1, 37, 24, 109943)),
        ),
    ]
