# Generated by Django 3.1 on 2020-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='9a3s0R7XyyGHoo3dyxGGff5cZ1QpbGs6', max_length=32),
        ),
    ]
