# Generated by Django 3.1 on 2020-08-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200822_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='3HwG5DYzG5dYGSMd4VtTFAGraSgvq73z', max_length=32),
        ),
    ]
