# Generated by Django 3.1 on 2020-08-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200822_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='XdHxS9dEnPEzWTtIVusNdcfBOKghhsYl', max_length=32),
        ),
    ]
