# Generated by Django 3.1 on 2020-08-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200822_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='AEl4dI1fWEPZGIPGugFjgeQhorKVRMO2', max_length=32),
        ),
    ]
