# Generated by Django 3.1 on 2020-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200822_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='kQmtJScCc4e2BQiSf6zWCHRhWSEiPlx1', max_length=32),
        ),
    ]
