# Generated by Django 3.1 on 2020-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200822_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='kTZnnyx3QZqxq9R4m1tXX5zcvp8AfiPn', max_length=32),
        ),
    ]
