# Generated by Django 3.1 on 2020-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200822_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='1YbrVeYcPPaR27doPHZcDVTDL0udEINh', max_length=32),
        ),
    ]
