# Generated by Django 3.1 on 2020-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200822_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='r0x9IRslU6O7xQ5xT6WeC4BoiEXAXA3C', max_length=32),
        ),
    ]
