# Generated by Django 3.1 on 2020-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200822_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='yVVjYcKwQ53XxoLELK4HsyislokXx4ju', max_length=32),
        ),
    ]
