# Generated by Django 3.1 on 2020-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200822_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='jPVcLJskKAaYK9lFv5o83dMVbCgnXk6w', max_length=32),
        ),
    ]
