# Generated by Django 3.1 on 2020-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200822_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='IqOnbZWXhfpdnSweSgOuYLWWIs8vkhg3', max_length=32),
        ),
    ]
