# Generated by Django 3.1 on 2020-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200822_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='DsQP5TUYgRbdX9cXtxD5Xjfhibc6KWou', max_length=32),
        ),
    ]
