# Generated by Django 3.1 on 2020-08-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200822_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='N9yi7YwSRqAJE5619rh5TW29IE2mgQW1', max_length=32),
        ),
    ]
