# Generated by Django 3.1 on 2020-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200822_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='BWQDM9eeOX8xFvTX4jd4LvoU50xdYYOT', max_length=32),
        ),
    ]
