# Generated by Django 3.1 on 2020-08-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200822_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='LnRVdHQKWSn9SpcrP6nITG8Duvm6B32L', max_length=32),
        ),
    ]
