# Generated by Django 3.1 on 2020-08-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200823_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='uid',
            field=models.CharField(default='GrfZiD1IuQtPPm10e3ctmnz1hat7xhkY', max_length=32),
        ),
    ]
